services:
  - type: web
    name: bery-real-estate
    runtime: java
    buildCommand: ./mvnw clean install
    startCommand: java -jar target/bery-real-estate-0.0.1-SNAPSHOT.jar
    envVars:
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: REDIS_HOST
        sync: false
      - key: REDIS_PORT
        sync: false
      - key: REDIS_PASSWORD
        sync: false
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION_MS
        sync: false
      - key: FORGOT_PW_EXPIRATION_MS
        sync: false
      - key: APP_BASE_URL
        sync: false
